#! /bin/sh

desk1=First
desk2=Second
desk3=Third
bspc monitor -d $desk1 $desk2 $desk3


#
# APPEARANCE
#

bspc config normal_border_color  "#eaffff"
bspc config focused_border_color "#121212"
bspc config active_border_color  "#ffeb16"

bspc config top_padding          2
bspc config right_padding        2
bspc config bottom_padding       12
bspc config left_padding         0
bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name left_ptr
xsetroot -solid "#808080"


#
# BEHAVIOR
#

# Do not allow applications or mouse movement to steal focus.
bspc config ignore_ewmh_focus true
bspc config focus_follows_pointer false


bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    false

~/bin/melonpanel
sakura &
