#! /bin/sh

#
# APPEARANCE
#

bspc config normal_border_color  "#55aaaa"
bspc config focused_border_color "#9eefef"
bspc config active_border_color  "#9eefef"

# Set top_padding to 2 if not using Polybar; Set to 0 if using Polybar.
bspc config top_padding          2
bspc config right_padding        2
bspc config bottom_padding       4
bspc config left_padding         0
bspc config border_width         4
bspc config window_gap           8

bspc config borderless_monocle   true
bspc config gapless_monocle      true

xsetroot -cursor_name center_ptr
xsetroot -solid "#757575"
xrdb -load ~/.Xdefaults &


#
# BEHAVIOR
#

bspc config split_ratio           0.59
bspc config ignore_ewmh_focus     true
bspc config focus_follows_pointer false

bspc config remove_disabled_monitors      false
bspc config merge_overlapping_monitors    false

# Sync the X11 clipboards PRIMARY (mouse selection) and CLIPBOARD (copy/paste commands).
pgrep -x autocutsel || /usr/bin/autocutsel -f -s PRIMARY

bspc rule -a zathura floating=off

# Adjust window size and position using the mouse and keys.
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
