#!/bin/bash
#
# Displays battery statistics for usage in menus, e.g
# i3blocks or i3status.

if [ $(uname -s) = "Linux" ]; then
    cmd='upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep state'
fi


if [ $(uname -s) = "OpenBSD" ]; then
    is_charging=$(apm -a)
    if [ ${is_charging} = "1" ]; then
        echo "Charging"
        exit 0
    fi
    cmd="apm -m"
fi

output=$(${cmd})
echo ${output}

