#!/bin/bash
#
# Displays battery statistics for usage in menus, e.g
# i3blocks or i3status.

if [ $(uname -s) = "Linux" ]; then
    cmd='acpi -b | grep "^Battery" | cut -d, -f3 | cut -d: --fields=1,2'
fi


if [ $(uname -s) = "OpenBSD" ]; then
    is_charging=$(apm -a)
    if [ ${is_charging} = "1" ]; then
        echo "Charging"
        exit 0
    fi
    cmd="apm -m"
fi

if [ $(uname -s) = "Darwin" ]; then
    cmd="pmset -g batt | grep -Eo '([0-9][0-9][0-9]):[0-5][0-9]'"
fi

output=$(${cmd})
echo ${output}

