#!/bin/bash
##
## Reloads the current page in Firefox, but preserve
## the scroll location.
## Requires MozRepl to be running locally at port 4242.
##
## Consider using the `-w` flag to nc.

hostname="localhost"
port="4242"
echo 'y = content.window.pageYOffset; x = content.window.pageXOffset; BrowserReload(); content.window.scrollTo(x,y); repl.quit();' | nc $hostname $port 2>&1 > /dev/null 