#!/bin/sh
#
# Kills the touchpad and enables scrolling using mouse
# button 2 and the pointing stick.

synclient TouchpadOff=1

# Activate scroll wheel button.
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Timeout" 50
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Inertia" 3

# Increase pointer speed.
xinput set-prop "/dev/wsmouse" "Device Accel Constant Deceleration" 0.4


