#!/bin/bash
##
## Locks the screen using i3lock or the Mac OS X system locker.
##


## MAC OS X
os="$(uname)"
if [ "x${os}" = "xDarwin" ]; then
  /System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend
fi

if [ "x${os}" = "xLinux" ]; then
  locker="/usr/bin/i3lock"
  if [ ! -f $locker ];then
      # Just blank screens.
      /usr/bin/xset dpms force suspend
      exit 0
  fi
fi

${locker} -c 000000
