#!/bin/bash

if [ $(uname) = "Darwin" ]; then
  osascript -e 'set volume output muted true'
  mute_res=${?}
  if [ ${mute_res} -ne 0 ]; then
    echo "ERROR: Cannot mute"
    exit 1
  fi
  exit 0
fi


if [ $(uname) = "Linux" ]; then
  output="$(/usr/bin/amixer set Master toggle)"
  mute_res=${?}
  if [ ${mute_res} -ne 0 ]; then
    echo "ERROR: Cannot toggle mute"
    exit 1
  fi
  exit 0
fi

if [ $(uname) = "OpenBSD" ]; then
  output="$(/usr/bin/mixerctl -t outputs.spkr_mute)"
  mute_res="${?}"
   if [ ${mute_res} -ne 0 ]; then
     echo "ERROR: Cannot toggle mute"
     exit 1
   fi
fi

