#!/bin/bash
##
## Mute volume, command line.
##

if [ $(uname) = "Darwin" ]; then
  ## Handle Mac
  osascript -e 'set volume output muted true'
  mute_res=${?}
  if [ ${mute_res} -ne 0 ]; then
    echo "ERROR: Cannot mute"
    exit 1
  fi
fi


if [ $(uname) = "Linux" ]; then
  output="$(/usr/bin/amixer set Master toggle)"
  mute_res=${?}
  if [ ${mute_res} -ne 0 ]; then
    echo "ERROR: Cannot toggle mute"
    exit 1
  fi
fi

