#!/bin/bash
##
## Creates a screenshot of a specified part of the display.
##

now=$(date +"%Y%m%d%H%M")
output="${HOME}/Desktop/skud-${now}.png"

if [ ${#} -eq 1 ]; then
  output=${1}
fi

if [ -f $output ]; then
    echo "Error: File ${output} already exists"
    exit 1
fi

gnome-screenshot -a -f ${output}

